// Side-effect imports: each panel registers itself with the UI manager.
import './ShopPanel';
import './InventoryPanel';
import './ProductionPanel';
import './AnimalPanel';
import './CharacterPanel';
import './EconomyPanels';
import './ProgressionPanels';
import './SettingsPanel';
import './WhatsNewPanel';
import './FarmhousePanel';
import './FriendsPanel';
import './MarketPanel';
import './LeaderboardPanel';
import './AccountPanels';
import './MoveFarmPanel';
import './NeighboursPanel';
import './FishingPanel';
import './AdminGiftPanel';
